export const NOTE_VIEWS_REQUEST = 'NOTE_VIEWS_REQUEST';
export const NOTE_VIEWS_SUCCESS = 'NOTE_VIEWS_SUCCESS';
export const NOTE_VIEWS_FAILED = 'NOTE_VIEWS_FAILED';


export const NOTE_VIEWSONE_REQUEST = 'NOTE_VIEWSONE_REQUEST';
export const NOTE_VIEWSONE_SUCCESS = 'NOTE_VIEWSONE_SUCCESS';
export const NOTE_VIEWSONE_FAILED = 'NOTE_VIEWSONE_FAILED';

export const NOTE_UPDATE_REQUEST = 'NOTE_UPDATE_REQUEST';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_FAILED = 'NOTE_UPDATE_FAILED';

export const NOTE_DELETE_REQUEST = 'NOTE_DELETE_REQUEST';
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS';
export const NOTE_DELETE_FAILED = 'NOTE_DELETE_FAILED';

export const NOTE_CREATE_REQUEST = 'NOTE_CREATE_REQUEST';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_FAILED = 'NOTE_CREATE_FAILED';


